version: '3'

services:

  serlo-content-crawler:
    image: serlo-content-crawler:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      CONTENT_URL: http://mbp.local:4040/resources
      CONTENT_USER: lehrer@schul-cloud.org
      CONTENT_PASSWORD: schulcloud
    ports:
      - 3000:3000
      - 9230:9230
    volumes:
      - .:/app
    command: npm run debug
